name: ashton_jones_medium_feed
description: An RSS feed of my Medium articles (https://tjgrapes.medium.com/)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

  google_fonts: ^1.1.1


  http: ^0.12.2 # https://pub.dev/packages/http
  webfeed: ^0.6.0 # https://pub.dev/packages/webfeed
  url_launcher: ^5.7.10 #https://pub.dev/packages/url_launcher


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
    - assets/